import Foundation

/// Strings are written in Russian in the code and serve as keys; English comes from en.lproj/Localizable.strings
/// (generated by scripts/l10n/make_strings.py). The interface follows the first language of macOS that the app speaks,
/// and a language chosen for Screenshooter wins: in Settings, or in System Settings → Language & Region → Applications,
/// which is the same choice (the app's own `AppleLanguages`, see `InterfaceLanguage`). That is the localization macOS
/// itself picks for the app, so the interface, the menus and the system panels speak one language. It is picked once per
/// launch, so a new choice takes effect after a restart.
public enum Localization {
    /// "ru" or "en" for this launch.
    public static let current: String = {
        // First of all, before anything asks the bundle for its localizations: it keeps its first answer. Screenshooter
        // 1.2 kept the language under keys of its own and wrote it into `AppleLanguages` at every launch.
        InterfaceLanguage.migrate(choiceKey: "ScreenshooterLanguage", appliedKey: "ScreenshooterAppliedLanguage")
        // A development build without the bundle has no translations: the keys are Russian.
        guard Bundle.main.path(forResource: "en", ofType: "lproj") != nil else { return "ru" }
        return InterfaceLanguage.running
    }()

    /// Call as early as possible at launch.
    public static func apply() {
        _ = current
    }

    static func string(_ key: String) -> String {
        bundle?.localizedString(forKey: key, value: key, table: nil) ?? key
    }

    private static let bundle: Bundle? = {
        guard current != "ru", let path = Bundle.main.path(forResource: current, ofType: "lproj") else { return nil }
        return Bundle(path: path)
    }()
}

/// Localized string. `key` is the Russian text; `%@` placeholders are filled with `args`.
public func L(_ key: String, _ args: CVarArg...) -> String {
    let text = Localization.string(key)
    return args.isEmpty ? text : String(format: text, arguments: args)
}
